apiVersion: v1
kind: Service
metadata:
  name: main-gateway
  namespace: istio-system
  labels:
    istio: main-gateway
    app: main-gateway
spec:
  type: LoadBalancer
  selector:
    istio: main-gateway
    app: main-gateway
  ports:
    - name: http2
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: main-gateway
  namespace: istio-system
spec:
  selector:
    istio: main-gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
