apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  annotations:
    sidecar.istio.io/inject: "true"
    traffic.sidecar.istio.io/includeInboundPorts: "5000"

spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
