apiVersion: v1
kind: Service
metadata:
  name: producer
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: producer
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
